sudo: false
language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.3
  - 5.4
  - 5.5

matrix:
  fast_finish: true
  include:
    # test against the latest HHVM version by using a newer image
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # Use edge image until the next travis CI stable image update
  allow_failures:
    - php: 7.1
    - php: hhvm

install:
  - composer install
  - composer require satooshi/php-coveralls

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - travis_retry vendor/bin/coveralls
