sudo: false
language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

install:
  - composer install
  - composer require satooshi/php-coveralls '~1.0'

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - vendor/bin/coveralls
